export const hrCalculatorTranslations = {
  ru: {
    hrCalculator: {
      badge: 'InCORE · Финансовая HR-диагностика', title: 'Сколько денег ваша компания теряет из-за людей и процессов?', subtitle: 'За 5 минут оцените стоимость текучести, адаптации и недополученной производительности.', reset: 'Сбросить',
      company: { title: 'Данные компании', subtitle: '7 показателей, которые влияют на стоимость текучести' },
      fields: {
        averageSalary: { label: 'Средняя зарплата сотрудника', hint: 'рублей в месяц' }, departures: { label: 'Уволенных за год', hint: 'человек' }, rampMonths: { label: 'Срок выхода на результат', hint: 'месяцев до полной продуктивности' }, revenue: { label: 'Валовая выручка на сотрудника', hint: 'рублей в месяц' }, hrCount: { label: 'Количество HR-специалистов', hint: 'человек' }, hrSalary: { label: 'Зарплата HR-специалиста', hint: 'рублей в месяц' }, hiresCapacity: { label: 'Наймов в месяц на 1 HR', hint: 'закрытий вакансий' }
      },
      result: { label: 'Сколько денег теряет компания', year: 'в год', perDeparture: 'на одного уволившегося сотрудника', lostRevenue: 'Недополученная выручка', costPerHire: 'Стоимость одного найма' },
      loss: { title: 'Куда уходят деньги', subtitle: 'Три основные статьи стоимости замены сотрудника.', recruitment: { title: 'Работа HR по найму', detail: 'Сколько HR-ресурса уходит на одно закрытие вакансии' }, adaptation: { title: 'Зарплата до выхода на результат', detail: 'Зарплата сотрудника за период до полной продуктивности' }, revenue: { title: 'Недополученная выручка', detail: 'Выручка, которую компания не получает, пока сотрудник выходит на полную продуктивность' } },
      metrics: { lossPercent: 'Потери / годовая зарплата', productivityLoss: 'Потеря продуктивности', productivityLossDetail: 'суммарное время, которое все замены выходят на полную продуктивность', revenueRisk: 'Недополученная выручка', revenueRiskDetail: 'среднее значение в месяц', hrCapacity: 'Годовая мощность HR', hrCostYearSuffix: 'затраты на HR в год', adaptationCost: 'Стоимость выхода на результат', adaptationDetail: 'зарплата сотрудника до полной продуктивности', recruitmentCost: 'Затраты HR на один найм', recruitmentDetail: 'доля HR-ресурса, приходящаяся на одну замену', revenueGap: 'Недополученная выручка за период выхода', revenueGapDetail: 'теоретическая выручка, которую компания не получает до полной продуктивности', lossPerDeparture: 'Стоимость замены сотрудника', hrCost: 'Затраты на HR / год', turnoverCostEmployee: 'Потери на одного сотрудника' },
      scenario: { badge: 'Сценарий снижения текучести', title: 'Что будет, если увольнений станет на {{value}}% меньше?', description: 'Показываем в деньгах, сколько компания потенциально сохранит при меньшем числе замен.', slider: 'Снижение текучести', saving: 'Экономия в год', remaining: 'Увольнений останется' },
      next: { badge: 'Следующий уровень диагностики', title: 'Зарплата сотрудника показывает только часть реальной стоимости', description: 'InCORE помогает связать стоимость роли, скорость выхода на результат и финансовый эффект, чтобы управлять не только наймом, но и окупаемостью работы человека.', items: { resultCost: 'Стоимость результата', roleCost: 'Стоимость роли', contractRoi: 'ROI контракта', financialForecast: 'Прогноз финансового эффекта' }, cta: 'Получить полный разбор' },
      report: { title: 'Ваш финансовый срез', description: 'Дополнительные показатели рассчитаны на основе введённых вами данных.', close: 'Закрыть', loss: 'Общие потери', saving25: 'Эффект при -25% текучести', saving40: 'Эффект при -40% текучести', ramp: 'Суммарный период разгона' }, footer: 'InCORE · финансовая модель HR-эффекта', units: { months: 'мес.', hires: 'наймов', currency: '₽' }
    }
  },
  en: {
    hrCalculator: {
      badge: 'InCORE · Financial HR Diagnostic', title: 'How much money is your company losing because of people and processes?', subtitle: 'In 5 minutes, estimate the cost of turnover, ramp-up and lost productivity.', reset: 'Reset',
      company: { title: 'Company data', subtitle: '7 indicators that affect the cost of turnover' },
      fields: { averageSalary: { label: 'Average employee salary', hint: 'per month' }, departures: { label: 'Employees leaving per year', hint: 'people' }, rampMonths: { label: 'Time to productivity', hint: 'months to full productivity' }, revenue: { label: 'Gross revenue per employee', hint: 'per month' }, hrCount: { label: 'HR specialists', hint: 'people' }, hrSalary: { label: 'HR specialist salary', hint: 'per month' }, hiresCapacity: { label: 'Hires per month per HR', hint: 'closed vacancies' } },
      result: { label: 'Estimated financial loss', year: 'per year', perDeparture: 'per departure', lostRevenue: 'Lost revenue', costPerHire: 'Cost per hire' },
      loss: { title: 'Financial loss map', subtitle: 'Main components of the cost of replacing an employee.', recruitment: { title: 'HR recruitment cost', detail: 'HR effort required for one hire' }, adaptation: { title: 'Ramp-up salary cost', detail: 'Salary paid before full productivity' }, revenue: { title: 'Lost revenue', detail: 'Average revenue not generated during ramp-up' } },
      metrics: { lossPercent: 'Loss / annual salary', productivityLoss: 'Productivity loss', productivityLossDetail: 'total ramp-up time across replacements', revenueRisk: 'Revenue at risk', revenueRiskDetail: 'average monthly value', hrCapacity: 'Annual HR capacity', hrCostYearSuffix: 'annual HR cost', adaptationCost: 'Ramp-up cost', adaptationDetail: 'salary during time to productivity', recruitmentCost: 'Direct recruitment cost', recruitmentDetail: 'HR resource allocated to replacement', revenueGap: 'Revenue gap', revenueGapDetail: 'theoretical revenue during the full ramp-up period', lossPerDeparture: 'Cost per departure', hrCost: 'HR cost / year', turnoverCostEmployee: 'Loss per employee' },
      scenario: { badge: 'Turnover reduction scenario', title: 'If departures decrease by {{value}}%', description: 'The same financial model with fewer replacements. HR KPI becomes a clear business value.', slider: 'Turnover reduction', saving: 'Annual savings', remaining: 'Departures remaining' },
      next: { badge: 'Next level of diagnosis', title: 'Three categories do not show the full cost of a people decision', description: 'The real cost of a role includes outcome, speed to productivity, quality and financial impact. InCORE connects role, skill, outcome, event, contract and money.', items: { resultCost: 'Cost of outcome', roleCost: 'Cost of role', contractRoi: 'Contract ROI', financialForecast: 'Financial impact forecast' }, cta: 'Get full diagnosis' },
      report: { title: 'Your financial snapshot', description: 'Additional indicators are calculated from the data you entered.', close: 'Close', loss: 'Total loss', saving25: 'Impact at -25% turnover', saving40: 'Impact at -40% turnover', ramp: 'Total ramp-up period' }, footer: 'InCORE · financial HR impact model', units: { months: 'mo.', hires: 'hires', currency: 'RUB' }
    }
  },
  kk: {
    hrCalculator: {
      badge: 'InCORE · HR қаржылық диагностикасы', title: 'Компанияңыз адамдар мен процестердің салдарынан қанша ақша жоғалтады?', subtitle: '5 минутта кадр ауысымы, бейімделу және өнімділіктің жоғалу құнын бағалаңыз.', reset: 'Қалпына келтіру',
      company: { title: 'Компания деректері', subtitle: 'Кадр ауысымының құнына әсер ететін 7 көрсеткіш' },
      fields: { averageSalary: { label: 'Қызметкердің орташа жалақысы', hint: 'айына' }, departures: { label: 'Жылына жұмыстан кеткендер', hint: 'адам' }, rampMonths: { label: 'Нәтижеге шығу мерзімі', hint: 'толық өнімділікке дейінгі айлар' }, revenue: { label: 'Бір қызметкерге жалпы түсім', hint: 'айына' }, hrCount: { label: 'HR мамандарының саны', hint: 'адам' }, hrSalary: { label: 'HR маманының жалақысы', hint: 'айына' }, hiresCapacity: { label: '1 HR-ға айына найм саны', hint: 'жабылған вакансиялар' } },
      result: { label: 'Есептелген шығын', year: 'жылына', perDeparture: 'бір жұмыстан кетуге', lostRevenue: 'Жоғалған түсім', costPerHire: 'Бір найм құны' },
      loss: { title: 'Қаржылық шығын картасы', subtitle: 'Қызметкерді ауыстыру құнының негізгі бөліктері.', recruitment: { title: 'HR рекрутинг шығыны', detail: 'Бір наймға HR жұмысының құны' }, adaptation: { title: 'Бейімделу жалақысы', detail: 'Қызметкер толық өнімділікке жеткенге дейінгі жалақы' }, revenue: { title: 'Жоғалған түсім', detail: 'Бейімделу кезеңіндегі орташа алынбаған түсім' } },
      metrics: { lossPercent: 'Шығын / жылдық жалақы', productivityLoss: 'Өнімділік жоғалуы', productivityLossDetail: 'барлық ауыстырулардың жиынтық бейімделу уақыты', revenueRisk: 'Тәуекелдегі түсім', revenueRiskDetail: 'айлық орташа мән', hrCapacity: 'HR жылдық қуаты', hrCostYearSuffix: 'жылдық HR қоры', adaptationCost: 'Бейімделу құны', adaptationDetail: 'нәтижеге шығу кезеңіндегі жалақы', recruitmentCost: 'Тікелей рекрутинг шығыны', recruitmentDetail: 'ауыстыруға бөлінген HR ресурсы', revenueGap: 'Түсім алшақтығы', revenueGapDetail: 'толық бейімделу кезеңіндегі теориялық түсім', lossPerDeparture: 'Бір жұмыстан кету құны', hrCost: 'HR шығыны / жыл', turnoverCostEmployee: 'Бір қызметкерге шығын' },
      scenario: { badge: 'Кадр ауысымын азайту сценарийі', title: 'Егер жұмыстан кетулер {{value}}%-ға азайса', description: 'Ауыстыру саны азайғандағы сол қаржылық модель. HR көрсеткіші бизнеске түсінікті ақшаға айналады.', slider: 'Кадр ауысымын азайту', saving: 'Жылдық үнем', remaining: 'Қалған жұмыстан кетулер' },
      next: { badge: 'Диагностиканың келесі деңгейі', title: 'Үш бап кадрлық шешімнің толық құнын көрсетпейді', description: 'Рөлдің нақты құны нәтиже, оған жету жылдамдығы, сапа және қаржылық әсерді қамтиды. InCORE рөл, дағды, нәтиже, оқиға, келісімшарт және ақшаны байланыстырады.', items: { resultCost: 'Нәтиже құны', roleCost: 'Рөл құны', contractRoi: 'Келісімшарт ROI', financialForecast: 'Қаржылық әсер болжамы' }, cta: 'Толық диагнозды алу' },
      report: { title: 'Қаржылық көрсеткіштеріңіз', description: 'Қосымша көрсеткіштер енгізілген деректер бойынша есептелді.', close: 'Жабу', loss: 'Жалпы шығын', saving25: '-25% ауысым әсері', saving40: '-40% ауысым әсері', ramp: 'Жалпы бейімделу кезеңі' }, footer: 'InCORE · HR қаржылық әсер моделі', units: { months: 'ай', hires: 'найм', currency: 'RUB' }
    }
  },
  az: {
    hrCalculator: {
      badge: 'InCORE · Maliyyə HR diaqnostikası', title: 'Şirkətiniz insanlara və proseslərə görə nə qədər pul itirir?', subtitle: '5 dəqiqəyə kadr dövriyyəsi, adaptasiya və itirilmiş məhsuldarlığın dəyərini hesablayın.', reset: 'Sıfırla',
      company: { title: 'Şirkət məlumatları', subtitle: 'Kadr dövriyyəsinin dəyərinə təsir edən 7 göstərici' },
      fields: { averageSalary: { label: 'Orta əməkdaş maaşı', hint: 'aylıq' }, departures: { label: 'İldə işdən ayrılanlar', hint: 'nəfər' }, rampMonths: { label: 'Nəticəyə çıxış müddəti', hint: 'tam məhsuldarlığa qədər aylar' }, revenue: { label: 'Bir əməkdaşa ümumi gəlir', hint: 'aylıq' }, hrCount: { label: 'HR mütəxəssislərinin sayı', hint: 'nəfər' }, hrSalary: { label: 'HR mütəxəssisinin maaşı', hint: 'aylıq' }, hiresCapacity: { label: '1 HR üçün aylıq işə qəbul', hint: 'bağlanmış vakansiyalar' } },
      result: { label: 'Hesablanmış itki', year: 'ildə', perDeparture: 'bir ayrılma üçün', lostRevenue: 'İtirilmiş gəlir', costPerHire: 'Bir işə qəbulun dəyəri' },
      loss: { title: 'Maliyyə itkisi xəritəsi', subtitle: 'Əməkdaşın əvəzlənməsi xərclərinin əsas hissələri.', recruitment: { title: 'HR işə qəbul xərci', detail: 'Bir işə qəbul üçün HR əməyinin dəyəri' }, adaptation: { title: 'Adaptasiya maaşı', detail: 'Əməkdaş tam məhsuldarlığa çatana qədər ödənilən maaş' }, revenue: { title: 'İtirilmiş gəlir', detail: 'Adaptasiya dövründə əldə edilməyən orta gəlir' } },
      metrics: { lossPercent: 'İtki / illik maaş', productivityLoss: 'Məhsuldarlıq itkisi', productivityLossDetail: 'bütün əvəzləmələrin ümumi adaptasiya müddəti', revenueRisk: 'Risk altında olan gəlir', revenueRiskDetail: 'aylıq orta göstərici', hrCapacity: 'HR illik gücü', hrCostYearSuffix: 'illik HR fondu', adaptationCost: 'Adaptasiya dəyəri', adaptationDetail: 'nəticəyə çıxış dövründə maaş', recruitmentCost: 'Birbaşa işə qəbul xərci', recruitmentDetail: 'əvəzləməyə ayrılan HR resursu', revenueGap: 'Gəlir fərqi', revenueGapDetail: 'tam adaptasiya dövründə nəzəri gəlir', lossPerDeparture: 'Bir ayrılmanın dəyəri', hrCost: 'HR xərci / il', turnoverCostEmployee: 'Bir əməkdaşa itki' },
      scenario: { badge: 'Kadr dövriyyəsinin azaldılması ssenarisi', title: 'İşdən ayrılmalar {{value}}% azalarsa', description: 'Daha az əvəzləmə ilə eyni maliyyə modeli. HR göstəricisi sahibkar üçün aydın pul dəyərinə çevrilir.', slider: 'Dövriyyənin azalması', saving: 'İllik qənaət', remaining: 'Qalan ayrılmalar' },
      next: { badge: 'Diaqnostikanın növbəti səviyyəsi', title: 'Üç xərc maddəsi kadr qərarının tam qiymətini göstərmir', description: 'Rolün real dəyərinə nəticə, məhsuldarlığa çıxış sürəti, keyfiyyət və maliyyə təsiri daxildir. InCORE rol, bacarıq, nəticə, hadisə, müqavilə və pulu birləşdirir.', items: { resultCost: 'Nəticənin dəyəri', roleCost: 'Rolun dəyəri', contractRoi: 'Müqavilə ROI', financialForecast: 'Maliyyə təsiri proqnozu' }, cta: 'Tam diaqnostikanı al' },
      report: { title: 'Maliyyə göstəriciləriniz', description: 'Əlavə göstəricilər daxil etdiyiniz məlumatlar əsasında hesablanıb.', close: 'Bağla', loss: 'Ümumi itki', saving25: '-25% dövriyyə təsiri', saving40: '-40% dövriyyə təsiri', ramp: 'Ümumi adaptasiya müddəti' }, footer: 'InCORE · HR maliyyə təsiri modeli', units: { months: 'ay', hires: 'işə qəbul', currency: 'RUB' }
    }
  }
} as const;
