import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, UserPlus, Users, CheckCircle2, ArrowRight } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../contexts/AuthContext';

type RoleSkill = { weight:number; skills:{id:string;name:string}|null };
type Role = { id:string; name:string; description:string|null; role_skills:RoleSkill[] };
type Candidate = { id:string; full_name:string; email:string|null; source:string; role_id:string|null; skill_scores:Record<string,number>; status:string };

export function CEOCandidatesPage(){
  const {t}=useTranslation(); const {user}=useAuth(); const navigate=useNavigate();
  const [roles,setRoles]=useState<Role[]>([]); const [candidates,setCandidates]=useState<Candidate[]>([]); const [roleId,setRoleId]=useState('');
  const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [source,setSource]=useState('manual'); const [resume,setResume]=useState('');
  const [scores,setScores]=useState<Record<string,number>>({}); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [selectingId,setSelectingId]=useState<string|null>(null); const [error,setError]=useState(''); const [showForm,setShowForm]=useState(false);

  const selectedRole=useMemo(()=>roles.find(r=>r.id===roleId)||null,[roles,roleId]);
  const skills=useMemo(()=>selectedRole?.role_skills.flatMap(rs=>rs.skills?[rs.skills]:[])||[],[selectedRole]);
  const match=useMemo(()=>{
    if(!selectedRole||!skills.length)return 0;
    const validRoleSkills=selectedRole.role_skills.filter(rs=>rs.skills!==null);
    const total=validRoleSkills.reduce((sum,rs)=>sum+Number(rs.weight||0),0)||1;
    return Math.round(validRoleSkills.reduce((sum,rs)=>{const skill=rs.skills;return skill?sum+(Number(scores[skill.id]||0)*Number(rs.weight||0)):sum;},0)/total);
  },[selectedRole,skills,scores]);

  const load=async()=>{if(!user)return;setLoading(true);setError('');try{const {data:rs,error:re}=await supabase.from('roles').select('id,name,description,role_skills(weight,skills(id,name))').eq('is_active',true).order('created_at',{ascending:false});if(re)throw re;setRoles((rs||[]) as unknown as Role[]);const {data:cs,error:ce}=await supabase.from('candidates').select('id,full_name,email,source,role_id,skill_scores,status').eq('user_id',user.id).order('created_at',{ascending:false});if(ce)throw ce;setCandidates((cs||[]) as Candidate[]);}catch(e:any){setError(e?.message||t('candidates.error'));}finally{setLoading(false);}};
  useEffect(()=>{void load();},[user]);
  useEffect(()=>{if(!roleId&&roles[0])setRoleId(roles[0].id);},[roles,roleId]);
  useEffect(()=>{if(selectedRole){const initial:Record<string,number>={};selectedRole.role_skills.forEach(rs=>{const skill=rs.skills;if(skill)initial[skill.id]=scores[skill.id]??0;});setScores(initial);}},[roleId]);

  const save=async()=>{if(!user||!name.trim()||!roleId){setError(t('candidates.required'));return;}setSaving(true);setError('');try{const {data:company,error:companyError}=await supabase.from('companies').select('id').eq('user_id',user.id).maybeSingle();if(companyError)throw companyError;if(!company?.id)throw new Error(t('candidates.error'));const {error:insertError}=await supabase.from('candidates').insert({user_id:user.id,company_id:company.id,role_id:roleId,full_name:name.trim(),email:email.trim()||null,source,resume_text:resume.trim()||null,skill_scores:scores,status:'new'});if(insertError)throw insertError;setName('');setEmail('');setResume('');setScores({});setShowForm(false);await load();}catch(e:any){setError(e?.message||t('candidates.error'));}finally{setSaving(false);}};

  const selectExecutor=async(candidate:Candidate)=>{if(!user)return;setSelectingId(candidate.id);setError('');try{const {error:updateError}=await supabase.from('candidates').update({status:'selected'}).eq('id',candidate.id).eq('user_id',user.id);if(updateError)throw updateError;setCandidates(current=>current.map(item=>item.id===candidate.id?{...item,status:'selected'}:item));navigate(`/ceo/contracts/new?candidate=${encodeURIComponent(candidate.id)}`);}catch(e:any){setError(e?.message||t('candidates.selectionError'));}finally{setSelectingId(null);}};

  if(loading)return <div className="p-6 md:p-8 text-center text-[#000052]">{t('common.loading')}</div>;
  return <div className="w-full min-w-0 p-3 sm:p-4 md:p-8 space-y-5 md:space-y-6 overflow-x-hidden max-w-7xl mx-auto">
    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div className="flex items-start gap-2 min-w-0"><button onClick={()=>navigate('/ceo/roles/market')} className="shrink-0 p-2 rounded-xl hover:bg-[#000052]/5 text-[#000052]" aria-label="Back"><ArrowLeft className="w-5 h-5"/></button><div className="min-w-0"><h1 className="text-2xl md:text-3xl font-bold text-[#000052] break-words">{t('candidates.title')}</h1><p className="mt-1 text-sm text-gray-400 break-words">{t('candidates.subtitle')}</p></div></div><button onClick={()=>setShowForm(v=>!v)} className="w-full sm:w-auto shrink-0 flex items-center justify-center gap-2 px-5 py-3 rounded-xl bg-[#000052] text-white font-semibold"><UserPlus className="w-4 h-4"/>{t('candidates.add')}</button></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700 break-words">{error}</div>}
    {showForm&&<div className="bg-white rounded-2xl shadow-sm p-4 sm:p-6 space-y-5 min-w-0"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><label className="block"><span className="text-sm font-semibold text-[#000052]">{t('candidates.name')} *</span><input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl"/></label><label className="block"><span className="text-sm font-semibold text-[#000052]">{t('candidates.email')}</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl"/></label></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><label className="block"><span className="text-sm font-semibold text-[#000052]">{t('candidates.role')} *</span><select value={roleId} onChange={e=>setRoleId(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl bg-white">{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className="block"><span className="text-sm font-semibold text-[#000052]">{t('candidates.source')}</span><select value={source} onChange={e=>setSource(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl bg-white"><option value="manual">{t('candidates.manual')}</option><option value="hh">{t('candidates.hh')}</option></select></label></div><label className="block"><span className="text-sm font-semibold text-[#000052]">{t('candidates.resume')}</span><textarea value={resume} onChange={e=>setResume(e.target.value)} rows={4} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl resize-none"/></label>{selectedRole&&<div className="rounded-2xl border border-[#000052]/10 p-4 sm:p-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h2 className="font-bold text-[#000052]">{t('candidates.candidateMatch')}</h2><p className="text-xs text-gray-400 mt-1">{t('candidates.scoreHint')}</p></div><div className="text-2xl font-bold text-[#B8860B]">{match}%</div></div><div className="mt-5 space-y-4">{selectedRole.role_skills.map(rs=>{const skill=rs.skills;if(!skill)return null;return <div key={skill.id} className="grid grid-cols-[minmax(0,1fr)_80px] gap-3 items-center"><div className="min-w-0"><div className="text-sm font-medium text-[#000052] break-words">{skill.name}</div><div className="text-xs text-gray-400 mt-1">{Math.round(Number(rs.weight||0)*100)}%</div></div><input type="number" min="0" max="100" value={scores[skill.id]??0} onChange={e=>setScores({...scores,[skill.id]:Math.max(0,Math.min(100,Number(e.target.value)||0))})} className="w-full px-3 py-2 border border-gray-200 rounded-lg text-right"/></div>})}</div></div>}<button disabled={saving||!roles.length} onClick={()=>void save()} className="w-full md:w-auto px-5 py-3 rounded-xl bg-[#B8860B] text-white font-semibold disabled:opacity-50">{saving?'...':t('candidates.save')}</button></div>}
    {!roles.length&&<div className="bg-white rounded-2xl shadow-sm p-6 text-center"><p className="text-sm text-gray-500">{t('candidates.noRoles')}</p><button onClick={()=>navigate('/ceo/roles/decompose')} className="mt-4 px-4 py-2 rounded-xl bg-[#000052] text-white">{t('candidates.next')}</button></div>}
    {roles.length&&candidates.length===0&&!showForm?<div className="bg-white rounded-2xl shadow-sm p-8 text-center"><Users className="w-10 h-10 mx-auto text-[#000052]/30"/><h2 className="mt-3 font-bold text-[#000052]">{t('candidates.noCandidates')}</h2><p className="mt-2 text-sm text-gray-400">{t('candidates.emptyState')}</p></div>:null}
    {candidates.length>0&&<div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{candidates.map(c=><div key={c.id} className="bg-white rounded-2xl shadow-sm p-4 sm:p-5 min-w-0"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-full bg-[#000052]/5 flex items-center justify-center shrink-0"><Users className="w-5 h-5 text-[#000052]"/></div><div className="min-w-0 flex-1"><h3 className="font-semibold text-[#000052] break-words">{c.full_name}</h3><p className="text-xs text-gray-400 break-all mt-1">{c.email||'—'}</p></div>{c.status==='selected'&&<CheckCircle2 className="w-5 h-5 text-emerald-600 shrink-0"/>}</div><div className="mt-4 pt-4 border-t border-gray-100 flex items-center justify-between gap-3"><span className="text-sm text-gray-500">{t('candidates.score')}</span><span className="font-bold text-[#B8860B]">{Math.round(Object.values(c.skill_scores||{}).reduce((a,b)=>a+Number(b),0)/(Object.values(c.skill_scores||{}).length||1))}%</span></div>{c.status==='selected'?<button onClick={()=>navigate(`/ceo/contracts/new?candidate=${encodeURIComponent(c.id)}`)} className="mt-4 w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-[#000052] text-white font-semibold"><ArrowRight className="w-4 h-4"/>{t('candidates.createContract')}</button>:<button disabled={selectingId===c.id} onClick={()=>void selectExecutor(c)} className="mt-4 w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-[#000052] text-white font-semibold disabled:opacity-50">{selectingId===c.id?'...':t('candidates.selectExecutor')}</button>}</div>)}</div>}
  </div>;
}
