import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, LockKeyhole, WalletCards } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../contexts/AuthContext';
import { PLATFORM_FEE_PERCENT, money } from '../../lib/contractFinance';

type Contract = { id:string; title:string; company_id:string; status:string; contract_value:number|null; revenue:number|null; planned_revenue:number|null; escrow_amount:number|null; platform_fee:number|null; agent_payouts_total:number|null; company_profit:number|null; roi_percentage:number|null; total_locked:number|null; escrow_status:string|null };
type Stream = { id:string; title:string; percent:number; amount:number; status:string; unlock_status:string };

export function CEOContractFinanceActivationPage(){
  const {t}=useTranslation(); const {user}=useAuth(); const navigate=useNavigate(); const {id=''}=useParams();
  const [contract,setContract]=useState<Contract|null>(null); const [streams,setStreams]=useState<Stream[]>([]); const [value,setValue]=useState(''); const [payoutPercent,setPayoutPercent]=useState('20');
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [funding,setFunding]=useState(false); const [error,setError]=useState('');

  const load=async()=>{if(!user||!id){setLoading(false);return;}try{const {data:c,error:ce}=await supabase.from('contracts').select('id,title,company_id,status,contract_value,revenue,planned_revenue,escrow_amount,platform_fee,agent_payouts_total,company_profit,roi_percentage,total_locked,escrow_status').eq('id',id).maybeSingle();if(ce)throw ce;if(!c)throw new Error(t('candidates.financeNotFound'));const {data:company,error:companyError}=await supabase.from('companies').select('id').eq('id',c.company_id).eq('user_id',user.id).maybeSingle();if(companyError)throw companyError;if(!company)throw new Error(t('candidates.financeForbidden'));if(!['DRAFT','ACTIVE'].includes(c.status))throw new Error(t('candidates.financeAlreadyActive'));const {data:s,error:se}=await supabase.from('contract_payout_streams').select('id,title,percent,amount,status,unlock_status').eq('contract_id',id).order('percent',{ascending:false});if(se)throw se;setContract(c as Contract);setStreams((s||[]) as Stream[]);setValue(String(c.contract_value||''));}catch(e:any){setError(e?.message||t('candidates.error'));}finally{setLoading(false);}};
  useEffect(()=>{void load();},[user,id]);

  const numericValue=money(value); const payoutPool=Math.round(numericValue*(Math.max(0,Math.min(100,Number(payoutPercent)||0))/100)); const fee=Math.round(payoutPool*PLATFORM_FEE_PERCENT/100); const projectedProfit=Math.max(0,numericValue-payoutPool-fee); const projectedRoi=numericValue>0?Math.round(projectedProfit/numericValue*100):0;
  const allocations=useMemo(()=>{const total=streams.reduce((s,x)=>s+Number(x.percent||0),0);return streams.map(x=>({...x,calculated:total>0?Math.round(payoutPool*Number(x.percent||0)/total):0}));},[streams,payoutPool]);
  const isDraft=contract?.status==='DRAFT'; const isPendingFunding=contract?.status==='ACTIVE'&&contract?.escrow_status==='PENDING'; const isFunded=contract?.status==='ACTIVE'&&contract?.escrow_status==='FUNDED';

  const activate=async()=>{if(!contract||!numericValue||!streams.length){setError(t('candidates.financeRequired'));return;}if(Number(payoutPercent)<=0||Number(payoutPercent)>=100){setError(t('candidates.financePayoutPercentError'));return;}setSaving(true);setError('');try{const {error:ue}=await supabase.from('contracts').update({contract_value:numericValue,revenue:0,planned_revenue:numericValue,escrow_amount:payoutPool,platform_fee:0,agent_payouts_total:0,company_profit:0,roi_percentage:0,total_paid_to_agent:0,total_locked:0,escrow_status:'PENDING',status:'ACTIVE',execution_status:'ACTIVE'}).eq('id',contract.id).eq('company_id',contract.company_id).eq('status','DRAFT');if(ue)throw ue;for(const stream of allocations){const {error:se}=await supabase.from('contract_payout_streams').update({amount:stream.calculated,status:'LOCKED',unlock_status:'LOCKED',unlock_condition:'OUTCOME_VERIFIED'}).eq('id',stream.id).eq('contract_id',contract.id);if(se)throw se;}await load();}catch(e:any){setError(e?.message||t('candidates.error'));}finally{setSaving(false);}};

  const fund=async()=>{if(!contract)return;setFunding(true);setError('');try{const {error:fe}=await supabase.rpc('fund_contract_escrow',{p_contract_id:contract.id});if(fe)throw fe;await load();}catch(e:any){setError(e?.message||t('candidates.financeFundingError'));}finally{setFunding(false);}};

  if(loading)return <div className="p-6 md:p-8 text-center text-[#000052]">{t('common.loading')}</div>;
  return <div className="w-full min-w-0 p-3 sm:p-4 md:p-8 max-w-5xl mx-auto space-y-6 overflow-x-hidden">
    <div className="flex items-start gap-2"><button onClick={()=>navigate(`/ceo/contracts/${id}`)} className="shrink-0 p-2 rounded-xl hover:bg-[#000052]/5 text-[#000052]" aria-label={t('candidates.outcomeBack')}><ArrowLeft className="w-5 h-5"/></button><div className="min-w-0"><div className="flex items-center gap-2 text-[#B8860B] text-sm font-semibold"><WalletCards className="w-4 h-4"/>{t('candidates.financeActivation')}</div><h1 className="text-2xl md:text-3xl font-bold text-[#000052] mt-1 break-words">{contract?.title||t('candidates.financeActivation')}</h1><p className="text-sm text-gray-500 mt-1">{t('candidates.financeSubtitle')}</p></div></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700 break-words">{error}</div>}
    {isPendingFunding&&<div className="bg-white rounded-2xl shadow-sm p-5 sm:p-7 space-y-4"><div className="flex items-center gap-3"><LockKeyhole className="w-6 h-6 text-[#B8860B]"/><div><h2 className="font-bold text-[#000052]">{t('candidates.financeFundingTitle')}</h2><p className="text-sm text-gray-500 mt-1">{t('candidates.financeFundingPending')}</p></div></div><div className="rounded-xl bg-[#B8860B]/10 p-4"><div className="text-xs text-gray-500">{t('candidates.financeFundingAmount')}</div><div className="mt-1 text-2xl font-bold text-[#000052]">${Number(contract?.escrow_amount||0).toLocaleString()}</div></div><button disabled={funding} onClick={()=>void fund()} className="w-full sm:w-auto px-5 py-3 rounded-xl bg-[#000052] text-white font-semibold disabled:opacity-50">{funding?'...':t('candidates.financeFundEscrow')}</button></div>}
    {isFunded&&<div className="bg-white rounded-2xl shadow-sm p-6 sm:p-8 text-center"><CheckCircle2 className="w-12 h-12 mx-auto text-emerald-600"/><h2 className="mt-4 text-xl font-bold text-[#000052]">{t('candidates.financeFunded')}</h2><p className="mt-2 text-sm text-gray-500">{t('candidates.financeFundedInfo')}</p><div className="mt-5 text-lg font-bold text-[#B8860B]">${Number(contract?.total_locked||0).toLocaleString()}</div><button onClick={()=>navigate(`/ceo/contracts/${id}`)} className="mt-6 px-5 py-3 rounded-xl bg-[#000052] text-white font-semibold">{t('candidates.financeGoContract')}</button></div>}
    {isDraft&&<><div className="bg-white rounded-2xl shadow-sm p-4 sm:p-6 space-y-5"><div className="flex items-center gap-2"><LockKeyhole className="w-5 h-5 text-[#B8860B]"/><h2 className="font-bold text-[#000052]">{t('candidates.financeTerms')}</h2></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label><span className="text-sm font-semibold text-[#000052]">{t('candidates.contractValue')}</span><input type="number" min="1" value={value} onChange={e=>setValue(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl"/></label><label><span className="text-sm font-semibold text-[#000052]">{t('candidates.payoutPercent')}</span><input type="number" min="1" max="99" value={payoutPercent} onChange={e=>setPayoutPercent(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl"/></label></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><div className="rounded-xl bg-[#000052]/5 p-4"><div className="text-xs text-gray-500">{t('candidates.contractValue')}</div><div className="mt-1 font-bold text-[#000052]">${numericValue.toLocaleString()}</div></div><div className="rounded-xl bg-[#B8860B]/10 p-4"><div className="text-xs text-gray-500">{t('candidates.escrow')}</div><div className="mt-1 font-bold text-[#B8860B]">${payoutPool.toLocaleString()}</div></div><div className="rounded-xl bg-[#000052]/5 p-4"><div className="text-xs text-gray-500">{t('candidates.platformFee')}</div><div className="mt-1 font-bold text-[#000052]">${fee.toLocaleString()}</div></div><div className="rounded-xl bg-emerald-50 p-4"><div className="text-xs text-gray-500">{t('candidates.companyProfit')}</div><div className="mt-1 font-bold text-emerald-700">${projectedProfit.toLocaleString()}</div></div></div><div className="rounded-xl bg-[#000052]/5 p-4 text-sm text-[#000052]">{t('candidates.financeLockNotice')}</div></div><div className="bg-white rounded-2xl shadow-sm p-4 sm:p-6 space-y-4"><div><h2 className="font-bold text-[#000052]">{t('candidates.financeStreams')}</h2><p className="text-sm text-gray-500 mt-1">{t('candidates.financeStreamsHint')}</p></div><div className="space-y-3">{allocations.map(s=><div key={s.id} className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 rounded-xl border border-gray-100 p-4"><div className="min-w-0"><div className="font-semibold text-[#000052] break-words">{s.title}</div><div className="text-xs text-gray-400 mt-1">{s.percent}% · {t('candidates.eventPending')}</div></div><div className="text-lg font-bold text-[#000052]">${s.calculated.toLocaleString()}</div></div>)}</div><button disabled={saving||!numericValue||!streams.length} onClick={()=>void activate()} className="w-full sm:w-auto px-5 py-3 rounded-xl bg-[#000052] text-white font-semibold disabled:opacity-50">{saving?'...':t('candidates.activateFinance')}</button></div></>}
  </div>;
}
