import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowLeft, FileSignature, CheckCircle2, Target, ShieldCheck, Zap } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../contexts/AuthContext';

type Candidate = { id:string; full_name:string; email:string|null; role_id:string|null; status:string };
type Role = { id:string; name:string; description:string|null };
type RoleSkill = { id:string; skill_id:string; weight:number; skills:{id:string;name:string;description:string|null;expected_outcomes:unknown;verification_criteria:unknown}|null };
const asList=(value:unknown):string[]=>Array.isArray(value)?value.filter((item):item is string=>typeof item==='string'):[];
const EVENT_TYPE='OUTCOME_VERIFIED';
const eventKeyForSkill=(skillId:string)=>`contract_skill:${skillId}`;

export function CEOContractCreatePage(){
  const {t}=useTranslation(); const {user}=useAuth(); const navigate=useNavigate(); const [params]=useSearchParams();
  const candidateId=params.get('candidate')||'';
  const [candidate,setCandidate]=useState<Candidate|null>(null); const [role,setRole]=useState<Role|null>(null); const [roleSkills,setRoleSkills]=useState<RoleSkill[]>([]);
  const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [deadline,setDeadline]=useState('');
  const [kpiCalls,setKpiCalls]=useState('0'); const [kpiMeetings,setKpiMeetings]=useState('0'); const [kpiProposals,setKpiProposals]=useState('0'); const [kpiRevenue,setKpiRevenue]=useState('0'); const [targetClients,setTargetClients]=useState('0');
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [created,setCreated]=useState(false);

  useEffect(()=>{const load=async()=>{if(!user||!candidateId){setError(t('candidates.required'));setLoading(false);return;}try{const {data:c,error:ce}=await supabase.from('candidates').select('id,full_name,email,role_id,status').eq('id',candidateId).eq('user_id',user.id).maybeSingle();if(ce)throw ce;if(!c)throw new Error(t('candidates.selectionError'));if(c.status!=='selected')throw new Error(t('candidates.selectionError'));setCandidate(c as Candidate);const {data:r,error:re}=await supabase.from('roles').select('id,name,description').eq('id',c.role_id).eq('is_active',true).maybeSingle();if(re)throw re;if(!r)throw new Error(t('candidates.noRoles'));setRole(r as Role);const {data:rs,error:rse}=await supabase.from('role_skills').select('id,skill_id,weight,skills(id,name,description,expected_outcomes,verification_criteria)').eq('role_id',c.role_id).order('weight',{ascending:false});if(rse)throw rse;const canonical=(rs||[]) as unknown as RoleSkill[];if(!canonical.length)throw new Error(t('candidates.noRoleSkills'));setRoleSkills(canonical);setTitle(`${r.name} · ${c.full_name}`);setDescription(r.description||'');const d=new Date();d.setDate(d.getDate()+30);setDeadline(d.toISOString().slice(0,10));}catch(e:any){setError(e?.message||t('candidates.error'));}finally{setLoading(false);}};void load();},[user,candidateId,t]);
  const totalWeight=useMemo(()=>roleSkills.reduce((sum,rs)=>sum+Number(rs.weight||0),0),[roleSkills]);
  const weightIsValid=Math.abs(totalWeight-1)<0.001||Math.abs(totalWeight-100)<0.001;
  const eventDefinitions=useMemo(()=>roleSkills.filter(rs=>rs.skills).map(rs=>({skillId:rs.skill_id,eventKey:eventKeyForSkill(rs.skill_id),eventType:EVENT_TYPE,verification:asList(rs.skills!.verification_criteria),outcomes:asList(rs.skills!.expected_outcomes)})),[roleSkills]);

  const create=async()=>{if(!user||!candidate||!role||!roleSkills.length)return;if(!weightIsValid){setError(t('candidates.roleWeightsError'));return;}setSaving(true);setError('');let companyId='';let createdContractId='';let createdAgentId='';try{const {data:company,error:companyError}=await supabase.from('companies').select('id').eq('user_id',user.id).maybeSingle();if(companyError)throw companyError;if(!company?.id)throw new Error(t('candidates.error'));companyId=company.id;let {data:agent,error:agentError}=await supabase.from('agents').select('id').eq('company_id',company.id).eq('email',candidate.email||'').maybeSingle();if(agentError)throw agentError;if(!agent){const {data:newAgent,error:newAgentError}=await supabase.from('agents').insert({user_id:user.id,company_id:company.id,full_name:candidate.full_name,email:candidate.email||null,status:'ACTIVE',specialization:role.name}).select('id').single();if(newAgentError)throw newAgentError;agent=newAgent;createdAgentId=newAgent.id;}
    const {data:contract,error:contractError}=await supabase.from('contracts').insert({company_id:company.id,agent_id:agent.id,role_id:role.id,title:title.trim(),description:description.trim(),deadline,status:'DRAFT',kpi_calls:Number(kpiCalls)||0,kpi_meetings:Number(kpiMeetings)||0,kpi_proposals:Number(kpiProposals)||0,kpi_revenue:Number(kpiRevenue)||0,target_clients:Number(targetClients)||0,avg_check:0,min_check:0,target_conversion:20,payment_streams:[],escrow_amount:0,escrow_status:'PENDING',revenue:0,planned_revenue:0,agent_payouts_total:0,company_profit:0,roi_percentage:0,platform_fee:0,total_paid_to_agent:0,execution_status:'ACTIVE',execution_version:'1.0'}).select('id').single();if(contractError)throw contractError;createdContractId=contract.id;
    const models=eventDefinitions.map(def=>{const rs=roleSkills.find(item=>item.skill_id===def.skillId)!;return {contract_id:contract.id,role_skill_id:rs.id,skill_id:def.skillId,weight:Number(rs.weight||0),expected_outcomes:def.outcomes,verification_criteria:def.verification,event_key:def.eventKey,event_type:def.eventType,event_status:'PENDING'};});
    const {error:modelError}=await supabase.from('contract_skill_models').insert(models);if(modelError)throw modelError;
    const rules=eventDefinitions.map(def=>({contract_id:contract.id,rule_key:def.eventKey,version:1,active:true,conditions:{event_type:def.eventType,skill_id:def.skillId,verification_criteria:def.verification},actions:{on_verified:'MARK_SKILL_OUTCOME_VERIFIED',event_key:def.eventKey}}));
    const {error:ruleError}=await supabase.from('contract_rules').insert(rules);if(ruleError)throw ruleError;
    setCreated(true);
  }catch(e:any){if(createdContractId){await supabase.from('contract_skill_models').delete().eq('contract_id',createdContractId);await supabase.from('contract_rules').delete().eq('contract_id',createdContractId);await supabase.from('contracts').delete().eq('id',createdContractId).eq('company_id',companyId);}if(createdAgentId&&companyId){await supabase.from('agents').delete().eq('id',createdAgentId).eq('company_id',companyId);}setError(e?.message||t('candidates.error'));}finally{setSaving(false);}};

  if(loading)return <div className="p-6 md:p-8 text-center text-[#000052]">{t('common.loading')}</div>;
  return <div className="w-full min-w-0 p-3 sm:p-4 md:p-8 max-w-5xl mx-auto space-y-6 overflow-x-hidden"><div className="flex items-start gap-2"><button onClick={()=>navigate('/ceo/candidates')} className="shrink-0 p-2 rounded-xl hover:bg-[#000052]/5 text-[#000052]" aria-label="Back"><ArrowLeft className="w-5 h-5"/></button><div className="min-w-0"><div className="flex items-center gap-2 text-[#B8860B] text-sm font-semibold"><FileSignature className="w-4 h-4"/>{t('candidates.createContract')}</div><h1 className="text-2xl md:text-3xl font-bold text-[#000052] break-words mt-1">{t('candidates.contractTitle')}</h1><p className="text-sm text-gray-400 mt-1 break-words">{t('candidates.contractSubtitle')}</p></div></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700 break-words">{error}</div>}{created?<div className="bg-white rounded-2xl shadow-sm p-8 text-center"><CheckCircle2 className="w-12 h-12 mx-auto text-emerald-600"/><h2 className="mt-4 text-xl font-bold text-[#000052]">{t('candidates.contractCreated')}</h2><p className="mt-2 text-sm text-gray-500">{t('candidates.contractDraftInfo')}</p><button onClick={()=>navigate('/ceo/contracts')} className="mt-6 px-5 py-3 rounded-xl bg-[#000052] text-white font-semibold">{t('candidates.goContracts')}</button></div>:candidate&&role?<div className="space-y-5"><div className="bg-white rounded-2xl shadow-sm p-4 sm:p-6"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div><div className="text-xs text-gray-400">{t('candidates.name')}</div><div className="mt-1 font-semibold text-[#000052] break-words">{candidate.full_name}</div></div><div><div className="text-xs text-gray-400">{t('candidates.role')}</div><div className="mt-1 font-semibold text-[#000052] break-words">{role.name}</div></div></div></div>
    <div className="bg-white rounded-2xl shadow-sm p-4 sm:p-6 space-y-5"><div><div className="flex items-center gap-2"><Target className="w-5 h-5 text-[#B8860B]"/><h2 className="font-bold text-[#000052]">{t('candidates.canonicalModel')}</h2></div><p className="mt-1 text-sm text-gray-500">{t('candidates.canonicalModelHint')}</p></div><div className="space-y-3">{roleSkills.map(rs=>{if(!rs.skills)return null;const outcomes=asList(rs.skills.expected_outcomes);const verification=asList(rs.skills.verification_criteria);const eventKey=eventKeyForSkill(rs.skill_id);return <div key={rs.id} className="rounded-xl border border-gray-100 p-4"><div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2"><div className="min-w-0"><div className="font-semibold text-[#000052] break-words">{rs.skills.name}</div>{rs.skills.description&&<div className="text-sm text-gray-500 mt-1 break-words">{rs.skills.description}</div>}</div><span className="shrink-0 text-sm font-bold text-[#B8860B]">{Math.round(Number(rs.weight||0)*100)}%</span></div>{outcomes.length>0&&<div className="mt-3"><div className="text-xs font-semibold text-gray-400 uppercase">{t('candidates.outcome')}</div><ul className="mt-1 text-sm text-[#000052] list-disc pl-5">{outcomes.map((x,i)=><li key={`${rs.id}-o-${i}`}>{x}</li>)}</ul></div>}{verification.length>0&&<div className="mt-3"><div className="flex items-center gap-1 text-xs font-semibold text-gray-400 uppercase"><ShieldCheck className="w-3 h-3"/>{t('candidates.verification')}</div><ul className="mt-1 text-sm text-[#000052] list-disc pl-5">{verification.map((x,i)=><li key={`${rs.id}-v-${i}`}>{x}</li>)}</ul></div>}<div className="mt-4 rounded-lg bg-[#000052]/5 p-3"><div className="flex items-center gap-1 text-xs font-semibold text-gray-500"><Zap className="w-3 h-3"/>{t('candidates.event')}</div><div className="mt-1 text-sm font-medium text-[#000052] break-all">{eventKey}</div><div className="mt-1 text-xs text-gray-500">{t('candidates.eventPending')}</div></div></div>})}</div><div className={`rounded-xl p-3 text-sm ${weightIsValid?'bg-emerald-50 text-emerald-800':'bg-red-50 text-red-700'}`}>{weightIsValid?t('candidates.roleWeightsValid'):t('candidates.roleWeightsError')}</div></div>
    <div className="bg-white rounded-2xl shadow-sm p-4 sm:p-6 space-y-5"><label className="block"><span className="text-sm font-semibold text-[#000052]">{t('candidates.contractName')}</span><input value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl"/></label><label className="block"><span className="text-sm font-semibold text-[#000052]">{t('candidates.contractDescription')}</span><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl resize-none"/></label><label className="block"><span className="text-sm font-semibold text-[#000052]">{t('candidates.deadline')}</span><input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl"/></label><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label><span className="text-sm font-semibold text-[#000052]">{t('candidates.kpiCalls')}</span><input type="number" min="0" value={kpiCalls} onChange={e=>setKpiCalls(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl"/></label><label><span className="text-sm font-semibold text-[#000052]">{t('candidates.kpiMeetings')}</span><input type="number" min="0" value={kpiMeetings} onChange={e=>setKpiMeetings(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl"/></label><label><span className="text-sm font-semibold text-[#000052]">{t('candidates.kpiProposals')}</span><input type="number" min="0" value={kpiProposals} onChange={e=>setKpiProposals(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl"/></label><label><span className="text-sm font-semibold text-[#000052]">{t('candidates.kpiRevenue')}</span><input type="number" min="0" value={kpiRevenue} onChange={e=>setKpiRevenue(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl"/></label><label><span className="text-sm font-semibold text-[#000052]">{t('candidates.targetClients')}</span><input type="number" min="0" value={targetClients} onChange={e=>setTargetClients(e.target.value)} className="mt-2 w-full px-4 py-3 border border-gray-200 rounded-xl"/></label></div><div className="rounded-xl bg-[#000052]/5 p-4 text-sm text-[#000052]">{t('candidates.draftMoneyNotice')}</div><button disabled={saving||!title.trim()||!deadline||!roleSkills.length||!weightIsValid} onClick={()=>void create()} className="w-full sm:w-auto px-5 py-3 rounded-xl bg-[#000052] text-white font-semibold disabled:opacity-50">{saving?'...':t('candidates.saveContractDraft')}</button></div></div>:null}</div>;
}
