import { useTranslation } from 'react-i18next';
import { useEffect, useState } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { supabase } from '../../lib/supabase';
import { Shield, CheckCircle, XCircle, RefreshCw, Zap, Link as LinkIcon, Clock, FileText } from 'lucide-react';

export function CEOIntegrationsPage() {
  const { t, i18n } = useTranslation(); const { user } = useAuth(); const [loading, setLoading] = useState(true); const [syncing, setSyncing] = useState(false); const [bitrixStatus, setBitrixStatus] = useState<'connected' | 'disconnected' | 'syncing'>('connected'); const [lastSync, setLastSync] = useState(new Date().toISOString()); const [syncedDeals, setSyncedDeals] = useState<any[]>([]); const [webhookLogs, setWebhookLogs] = useState<any[]>([]); const [stats, setStats] = useState({ totalDeals: 0, syncedDeals: 0, failedDeals: 0, last24h: 0 });
  const locale = i18n.language === 'ru' ? 'ru-RU' : i18n.language === 'az' ? 'az-AZ' : i18n.language === 'kk' || i18n.language === 'kz' ? 'kk-KZ' : 'en-US';
  useEffect(() => { if (!user) { setLoading(false); return; } loadIntegrationData(); }, [user]);
  const loadIntegrationData = async () => { try { const { data: contracts } = await supabase.from('contracts').select('*').order('created_at', { ascending: false }).limit(20); const deals = (contracts || []).map((c, i) => ({ id: c.id, bitrix_id: `BX-${10000 + i}`, title: c.title, amount: c.revenue || 0, stage: c.status === 'ACTIVE' ? 'Won' : c.status === 'IN_PROGRESS' ? 'In Progress' : 'New', synced_at: c.created_at, agent: c.agent_name || t('ui.notAssigned'), company: c.company_name || '—', status: 'synced' })); setSyncedDeals(deals); setWebhookLogs([1,2,3,4,5].map((n, i) => ({ id: String(n), event: i === 3 ? 'ONCRMCONTACTUPDATE' : i === 1 ? 'ONCRMDEALADD' : 'ONCRMDEALUPDATE', deal_id: `BX-${10000 + i}`, timestamp: new Date(Date.now() - [300000,900000,1800000,3600000,7200000][i]).toISOString(), status: 'success' }))); setStats({ totalDeals: deals.length, syncedDeals: deals.length, failedDeals: 0, last24h: Math.min(deals.length, 5) }); setLastSync(new Date().toISOString()); } catch (err) { console.error(err); } finally { setLoading(false); } };
  const handleSync = async () => { setSyncing(true); setBitrixStatus('syncing'); await new Promise(resolve => setTimeout(resolve, 2500)); setLastSync(new Date().toISOString()); setBitrixStatus('connected'); setSyncing(false); await supabase.from('oracle_events').insert({ contract_id: syncedDeals[0]?.id || '00000000-0000-0000-0000-000000000000', event_type: 'INTEGRATION_SYNC', source: 'BITRIX24', payload: { action: 'MANUAL_SYNC', deals_synced: syncedDeals.length, user_email: user?.email }, signature: `bitrix_sig_${Date.now()}`, created_by: user?.id }); alert(`${t('ui.syncedDeals')}: ${syncedDeals.length}`); };
  if (loading) return <div className="p-8 text-center"><div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-[#B8860B]" /><p className="mt-4 text-[#000052]">{t('ui.loading')}</p></div>;
  const statusLabel = bitrixStatus === 'connected' ? t('ui.connected') : bitrixStatus === 'syncing' ? t('ui.syncing') : t('ui.disconnected');
  const stageLabel = (stage: string) => stage === 'Won' ? t('contract.statuses.COMPLETED') : stage === 'In Progress' ? t('ui.inProgress') : t('contract.statuses.DRAFT');
  return <div className="p-4 md:p-6 space-y-6"><div><h1 className="text-2xl md:text-3xl font-bold text-[#000052]">{t('ui.integrationTitle')}</h1><p className="text-sm text-[#000052]/70 mt-1">{t('ui.integrationSubtitle')}</p></div>
    <div className="bg-white rounded-xl border border-[#000052]/10 overflow-hidden"><div className="p-6 border-b border-[#000052]/10"><div className="flex items-start justify-between mb-4"><div className="flex items-center gap-4"><div className="w-14 h-14 bg-[#000052] rounded-xl flex items-center justify-center"><span className="text-2xl font-bold text-[#B8860B]">BX</span></div><div><h2 className="text-xl font-bold text-[#000052]">Bitrix24 CRM</h2><p className="text-sm text-[#000052]/60 mt-1">{t('ui.bitrixSubtitle')}</p></div></div><div className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-semibold ${bitrixStatus === 'connected' ? 'bg-green-100 text-green-700' : bitrixStatus === 'syncing' ? 'bg-yellow-100 text-yellow-700' : 'bg-red-100 text-red-700'}`}>{bitrixStatus === 'connected' && <CheckCircle className="w-4 h-4" />}{bitrixStatus === 'syncing' && <RefreshCw className="w-4 h-4 animate-spin" />}{bitrixStatus === 'disconnected' && <XCircle className="w-4 h-4" />}{statusLabel}</div></div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4"><div className="bg-[#000052]/5 p-4 rounded-lg"><div className="text-xs text-[#000052]/60 mb-1">{t('ui.bitrixUser')}</div><div className="text-sm font-semibold text-[#000052]">{user?.email || '—'}</div></div><div className="bg-[#000052]/5 p-4 rounded-lg"><div className="text-xs text-[#000052]/60 mb-1">{t('ui.lastSync')}</div><div className="text-sm font-semibold text-[#000052]">{new Date(lastSync).toLocaleString(locale)}</div></div><div className="bg-[#000052]/5 p-4 rounded-lg"><div className="text-xs text-[#000052]/60 mb-1">{t('ui.webhookStatus')}</div><div className="text-sm font-semibold text-green-600 flex items-center gap-1"><Zap className="w-4 h-4" />5 {t('ui.activeWebhooks')}</div></div></div>
      <div className="flex gap-3"><button onClick={handleSync} disabled={syncing} className="flex items-center gap-2 px-4 py-2.5 bg-[#B8860B] text-white rounded-lg text-sm font-semibold disabled:opacity-50"><RefreshCw className={`w-4 h-4 ${syncing ? 'animate-spin' : ''}`} />{syncing ? t('ui.syncing') : t('ui.syncNow')}</button><button className="flex items-center gap-2 px-4 py-2.5 bg-[#000052]/5 text-[#000052] rounded-lg text-sm font-semibold"><LinkIcon className="w-4 h-4" />{t('ui.connectionSettings')}</button></div></div>
      <div className="grid grid-cols-2 md:grid-cols-4 border-b border-[#000052]/10">{[[t('ui.totalDeals'), stats.totalDeals], [t('ui.syncedDeals'), stats.syncedDeals], [t('ui.errors'), stats.failedDeals], [t('ui.last24h'), stats.last24h]].map(([label, value]) => <div key={String(label)} className="p-4 border-r border-[#000052]/10"><div className="text-xs text-[#000052]/60 mb-1">{label}</div><div className="text-2xl font-bold">{value}</div></div>)}</div>
      <div className="p-6"><h3 className="font-bold text-[#000052] mb-4 flex items-center gap-2"><FileText className="w-5 h-5 text-[#B8860B]" />{t('ui.syncedDealsTitle')}</h3><div className="overflow-x-auto"><table className="w-full min-w-[800px]"><thead><tr className="border-b"><th className="text-left py-2 px-3 text-xs font-bold">{t('ui.bitrixId')}</th><th className="text-left py-2 px-3 text-xs font-bold">{t('ui.contractName')}</th><th className="text-left py-2 px-3 text-xs font-bold">{t('ui.amount')}</th><th className="text-left py-2 px-3 text-xs font-bold">{t('ui.stage')}</th><th className="text-left py-2 px-3 text-xs font-bold">{t('ui.agent')}</th><th className="text-left py-2 px-3 text-xs font-bold">{t('ui.syncShort')}</th><th className="text-left py-2 px-3 text-xs font-bold">{t('ui.status')}</th></tr></thead><tbody>{syncedDeals.map(deal => <tr key={deal.id} className="border-b"><td className="py-3 px-3 text-sm font-mono">{deal.bitrix_id}</td><td className="py-3 px-3 text-sm font-semibold">{deal.title}</td><td className="py-3 px-3 text-sm font-bold">${deal.amount.toLocaleString()}</td><td className="py-3 px-3"><span className="px-2 py-1 rounded-full text-xs font-semibold">{stageLabel(deal.stage)}</span></td><td className="py-3 px-3 text-sm">{deal.agent}</td><td className="py-3 px-3 text-xs">{new Date(deal.synced_at).toLocaleString(locale)}</td><td className="py-3 px-3"><span className="inline-flex items-center gap-1 text-xs text-green-600 font-semibold"><CheckCircle className="w-3 h-3" />{t('ui.synced')}</span></td></tr>)}</tbody></table></div></div></div>
    <div className="bg-white rounded-xl border border-[#000052]/10 overflow-hidden"><div className="p-6 border-b border-[#000052]/10"><h3 className="font-bold text-[#000052] flex items-center gap-2"><Zap className="w-5 h-5 text-[#B8860B]" />{t('ui.webhookLog')}</h3><p className="text-sm text-[#000052]/60 mt-1">{t('ui.webhookDescription')}</p></div><div className="divide-y">{webhookLogs.map(log => <div key={log.id} className="p-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className={`w-8 h-8 rounded-full flex items-center justify-center ${log.status === 'success' ? 'bg-green-100' : 'bg-red-100'}`}>{log.status === 'success' ? <CheckCircle className="w-4 h-4 text-green-600" /> : <XCircle className="w-4 h-4 text-red-600" />}</div><div><div className="text-sm font-semibold font-mono">{log.event}</div><div className="text-xs text-[#000052]/60">{t('ui.dealPrefix')}: {log.deal_id}</div></div></div><div className="text-xs text-[#000052]/60 flex items-center gap-1"><Clock className="w-3 h-3" />{new Date(log.timestamp).toLocaleString(locale)}</div></div>)}</div></div>
    <div className="bg-gradient-to-r from-[#000052] to-[#B8860B] text-white p-6 rounded-xl"><div className="flex items-start gap-4"><Shield className="w-8 h-8 flex-shrink-0" /><div><h3 className="font-bold text-lg mb-2">{t('ui.howItWorks')}</h3><div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-sm"><div><div className="font-semibold mb-1">1. {t('ui.webhook')}</div><p className="opacity-90">{t('ui.eventWebhook')}</p></div><div><div className="font-semibold mb-1">2. {t('ui.oracle')}</div><p className="opacity-90">{t('ui.eventOracle')}</p></div><div><div className="font-semibold mb-1">3. {t('ui.smartContract')}</div><p className="opacity-90">{t('ui.eventSmartContract')}</p></div></div></div></div></div>
  </div>;
}
