import React, { useMemo, useState } from 'react';

type Lang = 'ru' | 'en' | 'kk' | 'az';
type Props = { lang: Lang; role: string; bottleneck?: { name: string } };
type Text = Record<Lang, string>;
type Matrix = { red: Text; green: Text; blue: Text };

const ui: Record<Lang, { title:string; intro:string; red:string; green:string; blue:string; choose:string; plan:string; empty:string; d1:string; d2:string; d3:string }> = {
  ru:{title:'Матрица обесценивания и роста навыков 2026–2030',intro:'Сравни свои навыки с теми, которые дешевеют, растут в цене и только появляются.',red:'Падает в цене',green:'Растёт в цене',blue:'Появляется',choose:'Выбери направление',plan:'Твой план на 90 дней',empty:'Заполни от 5 до 7 способностей, чтобы определить главное узкое место.',d1:'Дни 1–30: определить критерий результата и получить первое доказательство.',d2:'Дни 31–60: применить навык минимум в пяти реальных задачах и измерить изменение результата.',d3:'Дни 61–90: собрать доказательства результата и повторить расчёт рыночной мощности.'},
  en:{title:'Skill value and growth matrix 2026–2030',intro:'Compare your skills with those losing value, gaining value and emerging.',red:'Declining in value',green:'Growing in value',blue:'Emerging',choose:'Choose a direction',plan:'Your 90-day plan',empty:'Complete 5–7 capabilities to identify your main bottleneck.',d1:'Days 1–30: define the result criterion and obtain your first proof.',d2:'Days 31–60: apply the skill in at least five real tasks and measure the change.',d3:'Days 61–90: collect proof of results and recalculate your market capacity.'},
  kk:{title:'Дағдылардың құнсыздануы мен өсу матрицасы 2026–2030',intro:'Құны төмендейтін, өсетін және пайда болатын дағдыларыңды салыстыр.',red:'Құны төмендейді',green:'Құны өседі',blue:'Пайда болады',choose:'Бағытты таңда',plan:'90 күндік жоспарың',empty:'Негізгі тар орынды анықтау үшін 5–7 қабілетті толтыр.',d1:'1–30 күн: нәтиже өлшемін анықтап, алғашқы дәлелді ал.',d2:'31–60 күн: дағдыны кемінде бес нақты міндетте қолданып, өзгерісті өлше.',d3:'61–90 күн: нәтиже дәлелдерін жинап, нарықтық қуатты қайта есепте.'},
  az:{title:'Bacarıqların dəyər itirməsi və artımı matrisi 2026–2030',intro:'Dəyəri azalan, artan və yeni yaranan bacarıqlarını müqayisə et.',red:'Dəyəri azalır',green:'Dəyəri artır',blue:'Yaranır',choose:'İstiqamət seç',plan:'90 günlük planın',empty:'Əsas darboğazı müəyyən etmək üçün 5–7 bacarıq doldur.',d1:'1–30 gün: nəticə meyarını müəyyən et və ilk sübutunu əldə et.',d2:'31–60 gün: bacarığı ən azı beş real tapşırıqda tətbiq et və dəyişikliyi ölç.',d3:'61–90 gün: nəticə sübutlarını topla və bazar gücünü yenidən hesabla.'}
};

const t=(ru:string,en:string,kk:string,az:string):Text=>({ru,en,kk,az});
const matrix:Record<string,Matrix>={
 sales:{red:t('Холодные звонки по скрипту, базовая квалификация лида, механическое заполнение CRM, шаблонные КП.','Scripted cold calls, basic lead qualification, mechanical CRM entry and template proposals.','Скрипт бойынша суық қоңыраулар, бастапқы лид біліктілігі, CRM-ді механикалық толтыру және шаблондық ұсыныстар.','Skript üzrə soyuq zənglər, ilkin lead kvalifikasiyası, CRM-in mexaniki doldurulması və şablon təkliflər.'),green:t('Выявление скрытых экономических потребностей, сложные переговоры с несколькими ЛПР, удержание маржинальности.','Hidden economic needs, complex negotiations with multiple decision-makers and margin protection.','Жасырын экономикалық қажеттіліктер, бірнеше шешім қабылдаушымен күрделі келіссөздер және маржаны қорғау.','Gizli iqtisadi ehtiyacların aşkarlanması, bir neçə qərarverənlə mürəkkəb danışıqlar və marjanın qorunması.'),blue:t('Управление гибридной воронкой человек + AI, персонализация предложений, прогноз оттока по данным CRM.','Human + AI funnel management, personalized proposals and CRM-based churn prediction.','Адам + AI воронкасын басқару, ұсыныстарды дербестендіру және CRM деректері бойынша кетуді болжау.','İnsan + AI hunisinin idarə edilməsi, təkliflərin fərdiləşdirilməsi və CRM məlumatları ilə itki proqnozu.')},
 marketing:{red:t('Ручной таргетинг, SEO-тексты «для галочки», базовый дизайн и механический постинг.','Manual targeting, checkbox SEO copy, basic design and mechanical posting.','Қолмен таргеттеу, формалды SEO мәтіндері, базалық дизайн және механикалық жариялау.','Manual geniş hədəfləmə, formal SEO mətnləri, əsas dizayn və mexaniki paylaşım.'),green:t('Юнит-экономика, глубокие интервью с клиентами, репутация и кросс-функциональная стратегия.','Unit economics, deep customer research, reputation and cross-functional strategy.','Unit-экономика, терең клиенттік зерттеу, бедел және кросс-функционалды стратегия.','Unit iqtisadiyyatı, dərin müştəri araşdırması, reputasiya və funksiyalararası strategiya.'),blue:t('Управление AI-агентами, first-party данные и интерактивный контент.','AI-agent orchestration, first-party data and interactive content.','AI-агенттерін басқару, first-party деректері және интерактивті контент.','AI agentlərinin idarə edilməsi, first-party məlumatları və interaktiv kontent.')},
 it:{red:t('Шаблонный код, ручное тестирование, базовая вёрстка и простые дашборды.','Boilerplate code, manual testing, basic layouts and simple dashboards.','Шаблондық код, қолмен тестілеу, базалық беттеу және қарапайым дашбордтар.','Şablon kod, manual test, əsas layout və sadə dashboardlar.'),green:t('Архитектура, понимание бизнес-домена, безопасность, производительность и технический долг.','Architecture, business-domain expertise, security, performance and technical debt.','Архитектура, бизнес-доменді түсіну, қауіпсіздік, өнімділік және техникалық қарыз.','Arxitektura, biznes domeni, təhlükəsizlik, performans və texniki borc.'),blue:t('AI-оркестрация, проверка AI-результатов и MLOps.','AI orchestration, AI-output validation and MLOps.','AI-оркестрациясы, AI нәтижелерін тексеру және MLOps.','AI orkestrasiya, AI nəticələrinin yoxlanması və MLOps.')},
 hr:{red:t('Массовый скрининг резюме, первичные интервью, документы и рутинная координация.','Mass CV screening, first interviews, paperwork and routine coordination.','Резюмелерді жаппай скринингтеу, алғашқы сұхбаттар, құжаттар және күнделікті үйлестіру.','Kütləvi CV skrininqi, ilkin müsahibələr, sənədləşmə və rutin koordinasiya.'),green:t('Проектирование ролей, производительная мощность команд, внутренняя мобильность и удержание.','Role design, productive team capacity, internal mobility and retention.','Рөлдерді жобалау, команданың өнімді қуаты, ішкі мобильдік және ұстап қалу.','Rolların dizaynı, komandanın məhsuldar gücü, daxili mobillik və saxlanma.'),blue:t('Алгоритмическая справедливость, предиктивная аналитика текучести и рабочие места человек + AI.','Algorithmic fairness, predictive attrition analytics and human + AI job design.','Алгоритмдік әділдік, кетуді болжау аналитикасы және адам + AI жұмыс орындарын жобалау.','Alqoritmik ədalət, işçi dövriyyəsinin proqnoz analitikası və insan + AI iş yerlərinin dizaynı.')},
 finance:{red:t('Ручной ввод документов, сведение таблиц и бюджетирование «от достигнутого».','Manual document entry, spreadsheet consolidation and incremental budgeting.','Құжаттарды қолмен енгізу, кестелерді біріктіру және өткенге сүйенген бюджеттеу.','Sənədlərin əl ilə daxil edilməsi, cədvəllərin birləşdirilməsi və keçmişə əsaslanan büdcələmə.'),green:t('Сценарное моделирование, управление денежным потоком и ROI людей и технологий.','Scenario modelling, cash-flow decisions and ROI of people and technology.','Сценарийлік модельдеу, ақша ағынын басқару және адамдар мен технологиялардың ROI.','Ssenari modelləşdirməsi, pul axınının idarəsi və insan və texnologiyaların ROI-si.'),blue:t('Аудит алгоритмических финансовых решений, токенизированные активы и ESG.','Algorithmic finance audit, tokenized assets and ESG-finance integration.','Алгоритмдік қаржылық шешімдер аудиті, токенделген активтер және ESG.','Alqoritmik maliyyə qərarlarının auditi, tokenləşdirilmiş aktivlər və ESG.')}
};

export default function GrowthMatrix({lang,role,bottleneck}:Props){
 const u=ui[lang];
 const key=useMemo(()=>{const r=role.toLowerCase();if(/маркет|market/.test(r))return 'marketing';if(/разраб|developer|it|әзір|inkişaf/.test(r))return 'it';if(/hr|персон|адам|insan/.test(r))return 'hr';if(/финанс|finance|қаржы|maliyy/.test(r))return 'finance';return 'sales';},[role]);
 const m=matrix[key]; const [active,setActive]=useState<'red'|'green'|'blue'>('green');
 return <section className="mt-6 rounded-2xl border border-slate-200 p-5 sm:p-7" aria-label={u.title}>
  <h2 className="text-2xl font-bold">{u.title}</h2><p className="mt-2 leading-7 text-slate-600">{u.intro}</p>
  <div className="mt-5 grid gap-3 md:grid-cols-3">{(['red','green','blue'] as const).map(k=><button key={k} type="button" onClick={()=>setActive(k)} aria-pressed={active===k} className={`rounded-xl border p-4 text-left transition ${active===k?'border-slate-900 bg-slate-50':'border-slate-200 bg-white hover:bg-slate-50'}`}><div className="text-sm font-bold">{u[k]}</div><p className="mt-2 text-sm leading-6 text-slate-600">{m[k][lang]}</p></button>)}</div>
  <div className="mt-5 rounded-xl bg-slate-50 p-5"><div className="font-semibold">{u[active]}</div><p className="mt-2 leading-7 text-slate-700">{m[active][lang]}</p></div>
  <div className="mt-5 rounded-xl border border-slate-200 p-5"><div className="font-semibold">{u.plan}</div>{bottleneck?<div className="mt-3 space-y-2 text-sm leading-6 text-slate-700"><p>{bottleneck.name}</p><p>{u.d1}</p><p>{u.d2}</p><p>{u.d3}</p></div>:<p className="mt-3 text-sm text-slate-600">{u.empty}</p>}</div>
 </section>;
}
