import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, CheckCircle2, Lightbulb, RefreshCw, Target, TrendingDown, TrendingUp } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { SkillDefinition } from '../../types/decomposition';

type MarketProfile = { source_type: 'vacancy' | 'resume'; text: string; salary: number | null; skills: string[] | null; title?: string; region?: string };
type Stat = { skill: SkillDefinition; vacancies: number; resumes: number; vacancyShare: number | null; resumeShare: number | null; gap: number | null; vacancySalaryMedian: number | null };
const MATCHES: Record<string, { names: string[]; patterns: string[] }> = {
  'Продажи корпоративного страхования': { names: ['Корпоративные продажи', 'Страхование', 'Продажи'], patterns: ['корпоративн', 'b2b', 'страхован', 'страховой', 'продаж'] },
  'Удержание клиентов': { names: ['Работа с клиентами', 'Развитие клиентской базы', 'Продление договоров'], patterns: ['удержан', 'продлен', 'пролонгац', 'клиентск'] },
  'Кросс-продажи': { names: ['Кросс-продажи'], patterns: ['кросс-продаж', 'cross-sell', 'cross sell', 'допродаж'] },
  'Выполнение плана продаж': { names: ['План продаж', 'Продажи'], patterns: ['план продаж', 'выполнения плана', 'выполнение плана', 'kpi'] },
  'Удержание 90 дней': { names: [], patterns: ['удержание 90', '90 дней', 'retention'] },
  'Долгосрочная результативность': { names: ['План продаж'], patterns: ['годовой результат', 'долгосрочн', 'годовых целей', 'kpi'] },
};
function median(values: number[]) { if (!values.length) return null; const sorted = [...values].sort((a, b) => a - b); const m = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[m] : Math.round((sorted[m - 1] + sorted[m]) / 2); }
function money(value: number | null) { return value === null ? '—' : `${new Intl.NumberFormat('ru-RU').format(Math.round(value))} ₽`; }
function matches(profile: MarketProfile, mapping: { names: string[]; patterns: string[] }) { const text = (profile.text || '').toLowerCase(); const skills = Array.isArray(profile.skills) ? profile.skills : []; return mapping.names.some(name => skills.includes(name)) || mapping.patterns.some(pattern => text.includes(pattern)); }
function recommendation(stat: Stat, rank: number) {
  const gap = stat.gap ?? 0;
  const weight = stat.skill.weight * 100;
  const intensity = gap >= 20 && weight >= 20 ? 'Критический' : gap >= 20 ? 'Высокий' : gap > 0 ? 'Средний' : 'Низкий';
  let action = 'Закрепить навык в профиле роли и регулярно проверять его наличие у кандидатов.';
  if (gap >= 20) action = stat.resumes === 0 ? 'Добавить навык в обязательный скрининг и отдельное практическое задание: рынок требует его, а подходящих резюме пока нет.' : 'Усилить скрининг и оценку навыка: сравнивать кандидатов по реальным кейсам, а не только по наличию навыка в резюме.';
  else if (gap > 0) action = 'Оставить навык в фокусе отбора, но не завышать порог: дефицит умеренный.';
  else if (gap <= -20) action = 'Не делать навык главным фильтром: кандидатов с ним больше, чем вакансий. Использовать его как дополнительный критерий.';
  else if (gap < 0) action = 'Навык доступен на рынке в достаточном количестве. Использовать как дополнительный критерий при равных кандидатах.';
  return { intensity, action, rank, weight };
}
export function RoleMarketAnalysis({ skills }: { skills: SkillDefinition[] }) {
  const [profiles, setProfiles] = useState<MarketProfile[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); const { data, error: queryError } = await supabase.from('market_profiles').select('source_type, text, salary, skills, title, region').order('created_at', { ascending: false }); if (queryError) { setError(`Не удалось загрузить данные рынка: ${queryError.message}`); setProfiles([]); } else setProfiles((data ?? []) as MarketProfile[]); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const stats = useMemo<Stat[]>(() => { const vacancies = profiles.filter(p => p.source_type === 'vacancy'); const resumes = profiles.filter(p => p.source_type === 'resume'); return skills.map(skill => { const mapping = MATCHES[skill.name] ?? { names: [skill.name], patterns: [skill.name.toLowerCase()] }; const mv = vacancies.filter(p => matches(p, mapping)); const mr = resumes.filter(p => matches(p, mapping)); const vacancyShare = vacancies.length ? mv.length / vacancies.length * 100 : null; const resumeShare = resumes.length ? mr.length / resumes.length * 100 : null; const gap = vacancyShare !== null && resumeShare !== null ? vacancyShare - resumeShare : null; const salaries = mv.map(p => p.salary).filter((v): v is number => v !== null); return { skill, vacancies: mv.length, resumes: mr.length, vacancyShare, resumeShare, gap, vacancySalaryMedian: median(salaries) }; }); }, [profiles, skills]);
  const ordered = useMemo(() => [...stats].sort((a, b) => (b.gap ?? -Infinity) - (a.gap ?? -Infinity)), [stats]);
  const critical = ordered.filter(s => (s.gap ?? -Infinity) >= 20); const surplus = ordered.filter(s => (s.gap ?? Infinity) <= -20); const balance = ordered.filter(s => s.gap !== null && s.gap > -20 && s.gap < 20);
  const recommendations = useMemo(() => critical.map((stat, index) => ({ stat, ...recommendation(stat, index + 1) })).sort((a, b) => b.stat.gap! - a.stat.gap!), [critical]);
  const topOpportunity = useMemo(() => [...stats].filter(s => s.gap !== null && s.gap > 0).sort((a, b) => ((b.gap ?? 0) * b.skill.weight) - ((a.gap ?? 0) * a.skill.weight))[0], [stats]);
  const marketSummary = useMemo(() => { if (!profiles.length) return ''; if (critical.length) return `Рынок показывает дефицит ${critical.length} навыка${critical.length === 1 ? '' : critical.length < 5 ? 'ов' : 'ов'}. В первую очередь стоит усиливать поиск и проверку кандидатов по навыкам с максимальным разрывом и весом роли.`; if (surplus.length) return 'Критического дефицита нет. Рынок кандидатов в целом покрывает требования роли, поэтому можно повышать точность отбора по наиболее важным для результата навыкам.'; return 'Рынок и предложение кандидатов находятся в относительном балансе. Основной резерв улучшения сейчас не в расширении поиска, а в качестве оценки кандидатов.'; }, [profiles.length, critical.length, surplus.length]);
  return <section className="bg-white rounded-2xl shadow-sm overflow-hidden">
    <div className="p-5 md:p-6 border-b border-gray-100"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-[#B8860B]/10 flex items-center justify-center"><BarChart3 className="w-5 h-5 text-[#B8860B]" /></div><div><h3 className="font-bold text-[#000052] text-lg">Карта рынка навыков</h3><p className="text-sm text-gray-500 mt-1">Рыночные данные сопоставлены с требованиями этой роли.</p></div></div><button onClick={() => void load()} className="inline-flex items-center gap-2 px-3 py-2 rounded-xl border border-gray-200 text-[#000052] text-sm font-semibold"><RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />Обновить</button></div></div>
    {loading ? <div className="p-10 text-center text-sm text-gray-400">Загружаем данные рынка…</div> : error ? <div className="p-5 text-sm text-red-700 bg-red-50">{error}</div> : !profiles.length ? <div className="p-8 text-center text-sm text-gray-500">Данные рынка пока не загружены.</div> : <div className="p-5 md:p-6">
      <div className="grid grid-cols-3 gap-3 mb-7"><div className="p-4 rounded-xl bg-red-50"><div className="text-xs text-red-500 uppercase">Дефицитных навыков</div><div className="text-2xl font-bold text-red-700 mt-1">{critical.length}</div></div><div className="p-4 rounded-xl bg-amber-50"><div className="text-xs text-amber-600 uppercase">Баланс рынка</div><div className="text-2xl font-bold text-[#B8860B] mt-1">{balance.length}</div></div><div className="p-4 rounded-xl bg-blue-50"><div className="text-xs text-blue-500 uppercase">Профицитных навыков</div><div className="text-2xl font-bold text-blue-700 mt-1">{surplus.length}</div></div></div>
      <div className="mb-4"><h4 className="font-bold text-[#000052]">Рыночный разрыв Skill Gap</h4><p className="text-xs text-gray-400 mt-1">Положительное значение = дефицит навыка на рынке. Отрицательное = профицит.</p></div>
      <div className="overflow-x-auto"><div className="min-w-[760px] grid grid-cols-1 gap-3">{ordered.map(stat => { const gap = stat.gap; const width = Math.min(100, Math.abs(gap ?? 0)); const bar = gap === null ? 'bg-gray-300' : gap >= 20 ? 'bg-red-500' : gap <= -20 ? 'bg-[#46618C]' : 'bg-[#B8860B]'; return <div key={stat.skill.name} className="grid grid-cols-[220px_1fr_90px] items-center gap-3"><div className="text-sm font-semibold text-[#000052]">{stat.skill.name}</div><div className="h-7 bg-gray-100 rounded-lg overflow-hidden"><div className={`${bar} h-full rounded-lg`} style={{ width: `${width}%` }} /></div><div className="text-right text-sm font-bold text-[#000052]">{gap === null ? '—' : `${gap > 0 ? '+' : ''}${gap.toFixed(1)} п.п.`}</div></div>; })}</div></div>
      <div className="mt-7 overflow-x-auto"><table className="w-full min-w-[900px]"><thead><tr className="bg-gray-50 text-xs text-gray-500 uppercase"><th className="text-left p-3">Навык</th><th className="text-left p-3">Вес роли</th><th className="text-left p-3">Вакансии</th><th className="text-left p-3">Резюме</th><th className="text-left p-3">Skill Gap</th><th className="text-left p-3">Зарплата</th></tr></thead><tbody className="divide-y divide-gray-100">{ordered.map(stat => <tr key={stat.skill.name}><td className="p-3 font-semibold text-[#000052]">{stat.skill.name}</td><td className="p-3 font-semibold text-[#B8860B]">{Math.round(stat.skill.weight * 100)}%</td><td className="p-3 text-sm">{stat.vacancies} <span className="text-xs text-gray-400">({stat.vacancyShare === null ? '—' : `${stat.vacancyShare.toFixed(1)}%`})</span></td><td className="p-3 text-sm">{stat.resumes} <span className="text-xs text-gray-400">({stat.resumeShare === null ? '—' : `${stat.resumeShare.toFixed(1)}%`})</span></td><td className={`p-3 font-bold ${stat.gap !== null && stat.gap >= 20 ? 'text-red-600' : stat.gap !== null && stat.gap <= -20 ? 'text-blue-700' : 'text-[#000052]'}`}>{stat.gap === null ? '—' : `${stat.gap > 0 ? '+' : ''}${stat.gap.toFixed(1)} п.п.`}</td><td className="p-3 text-sm">{money(stat.vacancySalaryMedian)}</td></tr>)}</tbody></table></div>

      <div className="mt-7 rounded-2xl border border-[#B8860B]/20 bg-gradient-to-br from-[#fffaf0] to-white overflow-hidden">
        <div className="p-5 border-b border-[#B8860B]/10"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-xl bg-[#B8860B]/10 flex items-center justify-center"><Lightbulb className="w-5 h-5 text-[#B8860B]" /></div><div><h4 className="font-bold text-[#000052] text-lg">Что делать по результатам рынка</h4><p className="text-sm text-gray-600 mt-1">Рекомендации учитывают не только Skill Gap, но и вес навыка в этой роли.</p></div></div></div>
        <div className="p-5 space-y-4">
          <div className="flex items-start gap-3"><Target className="w-5 h-5 text-red-600 mt-0.5 shrink-0" /><div><div className="font-semibold text-[#000052]">Главный приоритет</div><div className="text-sm text-gray-700 mt-1">{recommendations.length ? <>{recommendations[0].stat.skill.name}: <strong>+{recommendations[0].stat.gap!.toFixed(1)} п.п.</strong> дефицита. В весе роли этот навык занимает <strong>{Math.round(recommendations[0].stat.skill.weight * 100)}%</strong>. Его нельзя компенсировать просто увеличением потока кандидатов, поэтому нужен отдельный критерий проверки.</> : <>Критического дефицита нет. Сохраняйте текущую структуру роли и используйте рынок для точной настройки отбора.</>}</div></div></div>
          {recommendations.length > 0 ? recommendations.slice(0, 3).map(item => <div key={item.stat.skill.name} className="rounded-xl bg-white border border-red-100 p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="w-6 h-6 rounded-full bg-red-50 text-red-700 text-xs font-bold flex items-center justify-center">{item.rank}</span><span className="font-bold text-[#000052]">{item.stat.skill.name}</span></div><div className="text-xs text-gray-500 mt-2">{item.intensity} приоритет · вес роли {Math.round(item.weight)}% · вакансии {item.stat.vacancyShare?.toFixed(1)}% · резюме {item.stat.resumeShare?.toFixed(1)}%</div></div><span className="text-red-600 font-bold whitespace-nowrap">+{item.stat.gap!.toFixed(1)} п.п.</span></div><div className="mt-3 p-3 rounded-lg bg-red-50/70 text-sm text-red-800"><strong>Действие:</strong> {item.action}</div>{item.stat.vacancySalaryMedian !== null && <div className="text-xs text-gray-500 mt-2">Медианная зарплата в вакансиях с этим навыком: <strong>{money(item.stat.vacancySalaryMedian)}</strong>.</div>}</div>) : <div className="rounded-xl bg-white border border-green-100 p-4"><div className="flex items-start gap-3"><CheckCircle2 className="w-5 h-5 text-green-600 mt-0.5" /><div><div className="font-semibold text-[#000052]">Рынок не показывает критического дефицита</div><div className="text-sm text-gray-600 mt-1">Фокусируйтесь на качестве оценки и на навыках с большим весом роли. Массово расширять требования не требуется.</div></div></div></div>}
          <div className="grid md:grid-cols-2 gap-3">
            <div className="p-4 rounded-xl bg-white border border-gray-100"><div className="flex items-center gap-2 text-sm font-semibold text-[#000052]"><TrendingUp className="w-4 h-4 text-red-500" />Для найма</div><div className="text-sm text-gray-600 mt-2">{recommendations.length ? `Сначала проверять ${recommendations.slice(0, 2).map(x => x.stat.skill.name).join(' и ')}. Не снижать требования к ключевым навыкам только ради увеличения воронки.` : 'Использовать веса роли как приоритет при сравнении кандидатов.'}</div></div>
            <div className="p-4 rounded-xl bg-white border border-gray-100"><div className="flex items-center gap-2 text-sm font-semibold text-[#000052]"><TrendingDown className="w-4 h-4 text-blue-600" />Для развития</div><div className="text-sm text-gray-600 mt-2">{topOpportunity ? `Развивать ${topOpportunity.skill.name}: он одновременно важен для роли (${Math.round(topOpportunity.skill.weight * 100)}%) и показывает положительный рыночный разрыв +${topOpportunity.gap!.toFixed(1)} п.п.` : 'Определить навыки с наибольшим весом роли и закрепить для них измеримые критерии результата.'}</div></div>
          </div>
          <div className="flex items-start gap-3 pt-1"><AlertTriangle className="w-4 h-4 text-[#B8860B] mt-0.5 shrink-0" /><div className="text-xs text-gray-500">{marketSummary}</div></div>
        </div>
      </div>

      <div className="mt-6"><h4 className="font-bold text-[#000052] mb-3">Связи между навыками</h4><div className="grid md:grid-cols-2 gap-2 text-sm"><div className="p-3 rounded-lg bg-gray-50"><strong>Продажи корпоративного страхования</strong> связаны с <strong>Удержанием клиентов</strong> 68%</div><div className="p-3 rounded-lg bg-gray-50"><strong>Продажи корпоративного страхования</strong> связаны с <strong>Кросс-продажами</strong> 62%</div><div className="p-3 rounded-lg bg-gray-50"><strong>Продажи корпоративного страхования</strong> усиливают <strong>Выполнение плана продаж</strong> 55%</div><div className="p-3 rounded-lg bg-gray-50"><strong>Удержание 90 дней</strong> требует <strong>Продаж корпоративного страхования</strong> 80%</div><div className="p-3 rounded-lg bg-gray-50"><strong>Долгосрочная результативность</strong> требует <strong>Удержания 90 дней</strong> 70%</div><div className="p-3 rounded-lg bg-gray-50"><strong>Долгосрочная результативность</strong> требует <strong>Выполнения плана продаж</strong> 65%</div></div></div>
    </div>}
  </section>;
}
