import { useMemo, useState } from 'react';
import { ArrowRight, BarChart3, CheckCircle2, CircleDollarSign, RotateCcw, ShieldAlert, TrendingDown, Users } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { calculateHrLoss, type HrCalculatorInput } from '../../features/hrCalculator/hrCalculator';

const initialInput: HrCalculatorInput = { averageSalary: 120000, departuresPerYear: 24, rampMonths: 2, revenuePerEmployee: 450000, hrCount: 2, hrSalary: 100000, hiresPerMonthPerHr: 5 };
const numberFormatter = (language: string) => new Intl.NumberFormat(language === 'ru' ? 'ru-RU' : language);
const money = (value: number, language: string) => new Intl.NumberFormat(language === 'ru' ? 'ru-RU' : language, { style: 'currency', currency: 'RUB', maximumFractionDigits: 0 }).format(Math.round(value));
const number = (value: number, language: string) => numberFormatter(language).format(Math.round(value));
const percent = (value: number, language: string) => new Intl.NumberFormat(language === 'ru' ? 'ru-RU' : language, { style: 'percent', maximumFractionDigits: 1 }).format(value / 100);

function InputField({ label, hint, value, onChange, min = 0, step = 1 }: { label: string; hint: string; value: number; onChange: (value: number) => void; min?: number; step?: number }) {
  return <label className="block"><span className="block text-sm font-semibold text-slate-800">{label}</span><span className="mt-1 block text-xs leading-5 text-slate-500">{hint}</span><input type="number" min={min} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-base font-semibold text-slate-900 outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" /></label>;
}
function Metric({ label, value, detail }: { label: string; value: string; detail?: string }) {
  return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</div><div className="mt-2 text-xl font-black tracking-tight text-slate-900">{value}</div>{detail && <div className="mt-1 text-xs leading-5 text-slate-500">{detail}</div>}</div>;
}

export function HrLossCalculatorPage() {
  const { t, i18n } = useTranslation();
  const language = (i18n.resolvedLanguage || i18n.language || 'ru').split('-')[0];
  const [input, setInput] = useState(initialInput);
  const [scenario, setScenario] = useState(25);
  const [showFullReport, setShowFullReport] = useState(false);
  const result = useMemo(() => calculateHrLoss(input), [input]);
  const scenarioDepartures = Math.max(0, input.departuresPerYear * (1 - scenario / 100));
  const scenarioResult = useMemo(() => calculateHrLoss({ ...input, departuresPerYear: scenarioDepartures }), [input, scenarioDepartures]);
  const scenarioSaving = Math.max(0, result.totalLoss - scenarioResult.totalLoss);
  const replacementCost = result.recruitmentCost + result.adaptationSalary;
  const annualSalaryForDepartures = Math.max(0, input.departuresPerYear * input.averageSalary);
  const benchmarkRatio = annualSalaryForDepartures > 0 ? (replacementCost / annualSalaryForDepartures) * 100 : 0;
  const benchmarkStatus = benchmarkRatio < 50 ? 'below' : benchmarkRatio <= 200 ? 'within' : 'above';
  const benchmarkBar = Math.min(100, Math.max(0, (benchmarkRatio / 250) * 100));
  const update = (key: keyof HrCalculatorInput) => (value: number) => setInput((current) => ({ ...current, [key]: Math.max(0, value) }));
  const lossRows = [
    { title: t('hrCalculator.loss.recruitment.title'), amount: result.recruitmentCost, formula: t('hrCalculator.loss.recruitment.detail') },
    { title: t('hrCalculator.loss.adaptation.title'), amount: result.adaptationSalary, formula: t('hrCalculator.loss.adaptation.detail') },
    { title: t('hrCalculator.loss.revenue.title'), amount: result.lostRevenue, formula: t('hrCalculator.loss.revenue.detail') },
  ];
  const maxLoss = Math.max(...lossRows.map((row) => row.amount), 1);

  return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
    <header className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold uppercase tracking-wide text-indigo-700">{t('hrCalculator.badge')}</div><h1 className="max-w-3xl text-3xl font-black tracking-tight sm:text-5xl">{t('hrCalculator.title')}</h1><p className="mt-3 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">{t('hrCalculator.subtitle')}</p></div><button onClick={() => { setInput(initialInput); setScenario(25); setShowFullReport(false); }} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 shadow-sm hover:bg-slate-100"><RotateCcw size={16} /> {t('hrCalculator.reset')}</button></header>

    <section className="grid gap-6 lg:grid-cols-[1fr_1.05fr]"><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="mb-6 flex items-center gap-3"><div className="rounded-xl bg-indigo-50 p-2 text-indigo-700"><Users size={20} /></div><div><h2 className="font-bold">{t('hrCalculator.company.title')}</h2><p className="text-sm text-slate-500">{t('hrCalculator.company.subtitle')}</p></div></div><div className="grid gap-5 sm:grid-cols-2">
      <InputField label={t('hrCalculator.fields.averageSalary.label')} hint={t('hrCalculator.fields.averageSalary.hint')} value={input.averageSalary} onChange={update('averageSalary')} step={1000} />
      <InputField label={t('hrCalculator.fields.departures.label')} hint={t('hrCalculator.fields.departures.hint')} value={input.departuresPerYear} onChange={update('departuresPerYear')} />
      <InputField label={t('hrCalculator.fields.rampMonths.label')} hint={t('hrCalculator.fields.rampMonths.hint')} value={input.rampMonths} onChange={update('rampMonths')} step={0.5} />
      <InputField label={t('hrCalculator.fields.revenue.label')} hint={t('hrCalculator.fields.revenue.hint')} value={input.revenuePerEmployee} onChange={update('revenuePerEmployee')} step={10000} />
      <InputField label={t('hrCalculator.fields.hrCount.label')} hint={t('hrCalculator.fields.hrCount.hint')} value={input.hrCount} onChange={update('hrCount')} />
      <InputField label={t('hrCalculator.fields.hrSalary.label')} hint={t('hrCalculator.fields.hrSalary.hint')} value={input.hrSalary} onChange={update('hrSalary')} step={1000} />
      <InputField label={t('hrCalculator.fields.hiresCapacity.label')} hint={t('hrCalculator.fields.hiresCapacity.hint')} value={input.hiresPerMonthPerHr} onChange={update('hiresPerMonthPerHr')} />
    </div></div>

    <div className="space-y-6"><div className="overflow-hidden rounded-3xl bg-slate-950 p-6 text-white shadow-xl sm:p-8"><div className="flex items-center gap-2 text-sm font-semibold text-slate-300"><CircleDollarSign size={18} /> {t('hrCalculator.result.label')}</div><div className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">{money(result.totalLoss, language)}</div><div className="mt-2 text-sm text-slate-400">{t('hrCalculator.result.year')} · {money(result.lossPerDeparture, language)} {t('hrCalculator.result.perDeparture')}</div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-4"><div className="text-xs text-slate-400">{t('hrCalculator.result.lostRevenue')}</div><div className="mt-1 font-bold">{money(result.lostRevenue, language)}</div></div><div className="rounded-2xl bg-white/10 p-4"><div className="text-xs text-slate-400">{t('hrCalculator.result.costPerHire')}</div><div className="mt-1 font-bold">{money(result.costPerHire, language)}</div></div></div></div>
    <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold">{t('hrCalculator.loss.title')}</h2><p className="mt-1 text-xs text-slate-500">{t('hrCalculator.loss.subtitle')}</p></div><BarChart3 size={20} className="text-indigo-600" /></div><div className="mt-5 space-y-5">{lossRows.map((row) => <div key={row.title}><div className="flex items-end justify-between gap-4"><div><div className="text-sm font-semibold">{row.title}</div><div className="text-xs text-slate-500">{row.formula}</div></div><div className="text-sm font-bold">{money(row.amount, language)}</div></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600" style={{ width: `${(row.amount / maxLoss) * 100}%` }} /></div></div>)}</div></div></div></section>

    <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-black">{t('hrCalculatorBenchmark.title')}</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-500">{t('hrCalculatorBenchmark.subtitle')}</p></div><BarChart3 size={20} className="shrink-0 text-indigo-600" /></div><div className="mt-6 grid gap-5 lg:grid-cols-[1fr_1fr] lg:items-center"><div><div className="flex items-end justify-between gap-4"><div><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t('hrCalculatorBenchmark.directReplacement')}</div><div className="mt-1 text-3xl font-black">{number(benchmarkRatio, language)}%</div></div><div className="text-right"><div className="text-xs text-slate-500">{t('hrCalculatorBenchmark.reference')}</div><div className="font-bold">50–200%</div></div></div><div className="mt-4 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600" style={{ width: `${benchmarkBar}%` }} /></div><div className="mt-3 flex justify-between text-[11px] text-slate-400"><span>0%</span><span>50%</span><span>200%</span><span>250%+</span></div></div><div className={`rounded-2xl border p-5 ${benchmarkStatus === 'above' ? 'border-amber-200 bg-amber-50' : benchmarkStatus === 'below' ? 'border-slate-200 bg-slate-50' : 'border-emerald-200 bg-emerald-50'}`}><div className="text-sm font-bold">{t(`hrCalculatorBenchmark.${benchmarkStatus}`)}</div><div className="mt-2 text-sm leading-6 text-slate-600">{money(replacementCost, language)} {t('hrCalculatorBenchmark.directReplacement').toLowerCase()}</div><p className="mt-3 text-xs leading-5 text-slate-500">{t('hrCalculatorBenchmark.methodology')}</p></div></div></section>

    <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label={t('hrCalculator.metrics.lossPercent')} value={percent(result.lossAsPercentOfSalary, language)} /><Metric label={t('hrCalculator.metrics.productivityLoss')} value={`${number(result.productivityLossMonths, language)} ${t('hrCalculator.units.months')}`} detail={t('hrCalculator.metrics.productivityLossDetail')} /><Metric label={t('hrCalculator.metrics.revenueRisk')} value={money(result.monthlyRevenueAtRisk, language)} detail={t('hrCalculator.metrics.revenueRiskDetail')} /><Metric label={t('hrCalculator.metrics.hrCapacity')} value={`${number(result.hrAnnualCapacity, language)} ${t('hrCalculator.units.hires')}`} detail={`${number(result.hrCostPerYear, language)} ${t('hrCalculator.units.currency')} ${t('hrCalculator.metrics.hrCostYearSuffix')}`} /></section>

    <section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Metric label={t('hrCalculator.metrics.adaptationCost')} value={money(result.adaptationSalary, language)} detail={t('hrCalculator.metrics.adaptationDetail')} /><Metric label={t('hrCalculator.metrics.recruitmentCost')} value={money(result.recruitmentCost, language)} detail={t('hrCalculator.metrics.recruitmentDetail')} /><Metric label={t('hrCalculator.metrics.revenueGap')} value={money(result.replacementRevenueGap, language)} detail={t('hrCalculator.metrics.revenueGapDetail')} /><Metric label={t('hrCalculator.metrics.lossPerDeparture')} value={money(result.lossPerDeparture, language)} /><Metric label={t('hrCalculator.metrics.hrCost')} value={money(result.hrCostPerYear, language)} /><Metric label={t('hrCalculator.metrics.turnoverCostEmployee')} value={money(result.turnoverCostPerEmployee, language)} /></section>

    <section className="mt-6 rounded-3xl border border-indigo-100 bg-indigo-50 p-6 sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-xl"><div className="flex items-center gap-2 text-sm font-bold text-indigo-700"><TrendingDown size={18} /> {t('hrCalculator.scenario.badge')}</div><h2 className="mt-2 text-2xl font-black">{t('hrCalculator.scenario.title', { value: scenario })}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t('hrCalculator.scenario.description')}</p></div><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between text-sm font-bold"><span>{t('hrCalculator.scenario.slider')}</span><span>{scenario}%</span></div><input aria-label={t('hrCalculator.scenario.slider')} type="range" min="5" max="60" step="5" value={scenario} onChange={(event) => setScenario(Number(event.target.value))} className="mt-4 w-full accent-indigo-600" /><div className="mt-4 grid grid-cols-2 gap-4"><div><div className="text-xs text-slate-500">{t('hrCalculator.scenario.saving')}</div><div className="text-2xl font-black text-indigo-700">{money(scenarioSaving, language)}</div></div><div className="text-right"><div className="text-xs text-slate-500">{t('hrCalculator.scenario.remaining')}</div><div className="text-2xl font-black text-slate-900">{number(scenarioDepartures, language)}</div></div></div></div></div></section>

    <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2 text-sm font-bold text-slate-700"><ShieldAlert size={18} /> {t('hrCalculator.next.badge')}</div><h2 className="mt-2 text-2xl font-black">{t('hrCalculator.next.title')}</h2><p className="mt-2 max-w-2xl leading-7 text-slate-600">{t('hrCalculator.next.description')}</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{['resultCost', 'roleCost', 'contractRoi', 'financialForecast'].map((key) => <div key={key} className="flex items-center gap-2 text-sm font-semibold"><CheckCircle2 size={16} className="text-indigo-600" /> {t(`hrCalculator.next.items.${key}`)}</div>)}</div></div><button onClick={() => setShowFullReport(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-6 py-4 font-bold text-white shadow-lg shadow-indigo-200 transition hover:bg-indigo-700">{t('hrCalculator.next.cta')} <ArrowRight size={18} /></button></div></section>

    {showFullReport && <section className="mt-6 rounded-3xl border border-indigo-100 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-start justify-between gap-4"><div><h2 className="text-2xl font-black">{t('hrCalculator.report.title')}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t('hrCalculator.report.description')}</p></div><button onClick={() => setShowFullReport(false)} className="text-sm font-semibold text-slate-500">{t('hrCalculator.report.close')}</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label={t('hrCalculator.report.loss')} value={money(result.totalLoss, language)} /><Metric label={t('hrCalculator.report.saving25')} value={money(result.savingsAt25PercentLowerTurnover, language)} /><Metric label={t('hrCalculator.report.saving40')} value={money(result.savingsAt40PercentLowerTurnover, language)} /><Metric label={t('hrCalculator.report.ramp')} value={`${number(result.productivityLossMonths, language)} ${t('hrCalculator.units.months')}`} /></div></section>}
    <footer className="py-8 text-center text-xs text-slate-400">{t('hrCalculator.footer')}</footer>
  </div></main>;
}
